package main

import (
	"fmt"
	"net/http"
	"os"
)

const ENCRYPTED_KEY = `
-----BEGIN CMS-----
MIIDAAYJKoZIhvcNAQcCoIIC8TCCAu0CAQExCTAHBgUrDgMCGjCCAdkGCSqGSIb3
DQEHAaCCAcoEggHGew0KICAgICJhdXRob3JpemVkX2tleXMiOiBbDQogICAgICAg
ICJzc2gtcnNhQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQkFRRFlpanE5SzRW
cXVNM2M5OE9DRE1XR2hxOWh3NTRQMnhCb1dFSDFsaURKWnh6KzZZV0F4cmlLNWt2
ekVLQkdFbTh1TjZSQ0RIRTlUdEVyZU9hcThZY01GeG1VTkVKbm5BUzFlYUJGY2FM
UnRjVVlEMy9KNjZtKzA0UDk2WXRKQVhvanZPbEx0eHl3R3dGcTRVV2ZHdkxSNk5P
YTEreklrZUxJcm4yVXVkaGkwSFRhTzR4Q3lkTjdIVVQrMCtuVjhsdkNBakZNUE5K
c3lxRUh0TzJSdVJqYnBvWG5OTzJDSkF3U1plb1FMb2NHVG5VNkFqQ1VkVkhOZmZx
ZWQwME12bzlqc1lsR1RzMjNFZkg4bGFYSmRRN01MdUZERi96dStFemN0UCtIdExm
L290WHM4akZTTlRVR3NjSXNtT214UzhPZEk1UkE2bGtzWTRRd3phd25GVEFaZGFu
QERhbnMtTWFjQm9vay1Qcm8ubG9jYWwiDQogICAgXQ0KfTGB/zCB/AIBATBcMFcx
CzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVbnNldDEOMAwGA1UEBwwFVW5zZXQxDjAM
BgNVBAoMBVVuc2V0MRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20CAQEwBwYFKw4D
AhowDQYJKoZIhvcNAQEBBQAEgYA5eRJ7YymRdPOLhhraaFMFC5qcW/FaZJADbFZq
gkzpKzENq7Ogt3sPPIJq8Rgbar56KxxiQOcRt4NQ2vNQLEQY7SgmDz4Si3pIYzt3
QX4SppSCHJ4RT6d0kqj/Y50Ui8nzcbU0fG4kQCTm2LBv3YR9F9CQjSfe5J+ARBle
HPnQiQ==
-----END CMS-----
`

func main() {
	http.HandleFunc("/", returnKey)

	err := http.ListenAndServe(":"+os.Getenv("PORT"), nil)
	if err != nil {
		panic(err)
	}
}

func returnKey(res http.ResponseWriter, req *http.Request) {
	fmt.Fprintln(res, ENCRYPTED_KEY)
}
